# Generated by Django 4.1.1 on 2022-10-05 19:53

from django.db import migrations


def create_data(apps, schema_editor):
    User = apps.get_model('wellness_app', 'User')
    User(
        name = "John Doe",
        email = "[email protected]",
        phone = "1234567890",
    ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('wellness_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
