# Generated by Django 4.1.1 on 2022-10-12 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wellness_app', '0002_create_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wellness_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='WellnessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('isCompleted', models.BooleanField(default=False)),
                ('isExpired', models.BooleanField(default=False)),
                ('wellnessType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellness_app.wellnesstype')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('emotions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellness_app.emotion')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellness_app.journal')),
                ('tasks', models.ManyToManyField(to='wellness_app.task')),
            ],
        ),
    ]
